import Foundation

class QuestionBank {
    
    var list = [ChoiceQuestion]()
    
    init(){
      let question1=ChoiceQuestion()
        question1.setText(question1: "Siapakah yang membacakan teks proklamasi Indonesia ?")
        question1.addChoice(choice: "Moh Hatta", correct: false)
        question1.addChoice(choice: "Soekarni", correct: false)
        question1.addChoice(choice: "Soekarno", correct: true)
        question1.addChoice(choice: "Sutan Syahrir", correct: false)
        let question2=ChoiceQuestion()
        question2.setText(question1: "Pembacaan teks proklamasi Indonesia dilaksanakan di alamat...")
        question2.addChoice(choice: "Lapangan Ikada", correct: false)
        question2.addChoice(choice: "Jalan Merdeka Barat", correct: false)
        question2.addChoice(choice: "Jalan Pegangsaan Timur", correct: true)
        question2.addChoice(choice: "Jalan Imam Bonjol", correct: false)
        let question3=ChoiceQuestion()
        question3.setText(question1: "Berikut ini yang merupakan salah satu dari golongan muda adalah...")
        question3.addChoice(choice: "Soekarno", correct: false)
        question3.addChoice(choice: "Soekarni", correct: true)
        question3.addChoice(choice: "Moh.Hatta", correct: false)
        question3.addChoice(choice: "Laksamana Maeda", correct: false)
        let question4=ChoiceQuestion()
        question4.setText(question1: "Nama gerakan dari golongan pemuda yang pempelopori penculikan Soekarno-Hatta adalah...")
        question4.addChoice(choice: "Gerakan Benteng 31", correct: false)
        question4.addChoice(choice: "Gerakan Banteng 31", correct: false)
        question4.addChoice(choice: "Gerakan Lenteng 31", correct: false)
        question4.addChoice(choice: "Gerakan Menteng 31", correct: true)
        let question5=ChoiceQuestion()
        question5.setText(question1: "Yang merupakan wilayah militer jepang di indonesia saat menguasai indonesia adalah tentara...")
        question5.addChoice(choice: "XXII/ Rikugun Bali", correct: false)
        question5.addChoice(choice: "XXV/ Rikugun Jakarta", correct: false)
        question5.addChoice(choice: "II/ Kaigun Sumatera Barat", correct: false)
        question5.addChoice(choice: "II/ Kaigun Makassar", correct: true)
        let question6=ChoiceQuestion()
        question6.setText(question1: "Apa yg menyebabkan terjadinya peristiwa rengasdengklok?")
        question6.addChoice(choice: "Perdebatan mengenai penyusun naskah Proklamasi", correct: false)
        question6.addChoice(choice: "Keadaan di Indonesia yang sedang genting", correct: false)
        question6.addChoice(choice: "Adanya perbedaan pendapat antara golongan tua dan golongan muda", correct: true)
        question6.addChoice(choice: "Adanya vacuum of power karena kekalahan Jepang", correct: false)
        let question7=ChoiceQuestion()
        question7.setText(question1: "At what temperature are Fahrenheit and Celsius the same?")
        question7.addChoice(choice: "0", correct: false)
        question7.addChoice(choice: "92", correct: true)
        question7.addChoice(choice: "50", correct: false)
        question7.addChoice(choice: "-40", correct: false)
        let question8=ChoiceQuestion()
        question8.setText(question1: "What are the odds of being killed by space debris?")
        question8.addChoice(choice: "1 in 1 trillion", correct: false)
        question8.addChoice(choice: "1 in 5 million", correct: false)
        question8.addChoice(choice: "1 in 5 billion", correct: true)
        question8.addChoice(choice: "1 in 10 billion", correct: false)
        let question9=ChoiceQuestion()
        question9.setText(question1: "The NY phone book had 22 Hitlers before WWII. How many did it have at the end of the twentieth century?")
        question9.addChoice(choice: "4", correct: true)
        question9.addChoice(choice: "0", correct: false)
        question9.addChoice(choice: "11", correct: false)
        question9.addChoice(choice: "13", correct: false)
        let question10=ChoiceQuestion()
        question10.setText(question1: "What percentage of Japanese citizens are cremated?")
        question10.addChoice(choice: "26", correct: false)
        question10.addChoice(choice: "5", correct: false)
        question10.addChoice(choice: "98", correct: true)
        question10.addChoice(choice: "11", correct: false)
        
        list.append(question1)
        list.append(question2)
        list.append(question3)
        list.append(question4)
        
      list.append(question5)
        list.append(question6)
        list.append(question7)
        list.append(question8)
        list.append(question9)
        list.append(question10)
    }
    
}
